name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore DevOpsProductApi.sln

      - name: Build application
        run: dotnet build DevOpsProductApi.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test DevOpsProductApi.sln --configuration Release --no-build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/bhavin21187/devops-product-api:${{ github.sha }} \
            -t ghcr.io/bhavin21187/devops-product-api:latest \
            .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/bhavin21187/devops-product-api:${{ github.sha }}
          docker push ghcr.io/bhavin21187/devops-product-api:latest